force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Adverse_Party_Invoice_Postal_Address__c.field-meta.xml
<CustomField>
    <fullName>Adverse_Party_Invoice_Postal_Address__c</fullName>
    <formula>Matter__r.Postal_Address__c</formula>
    <label>Adverse Party Invoice Postal Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BMA ADVOCATES LLP-CLIENT ACCOUNT</fullName>
            </value>
            <value>
                <fullName>HISA REGISTRARS-CLIENT ACCOUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <formula>Matter__r.Client__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Disbursement_Amount_Requested__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Amount_Requested__c</fullName>
    <label>Disbursement Amount Requested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Disbursement_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Invoice_Number__c</fullName>
    <label>Disbursement Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Include_Logo__c.field-meta.xml
<CustomField>
    <fullName>Include_Logo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Include Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Initials_and_Current_Date__c.field-meta.xml
<CustomField>
    <fullName>Initials_and_Current_Date__c</fullName>
    <formula>Initials__c +&quot;/&quot;+ Current_Month_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Initials and Current Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <externalId>true</externalId>
    <label>Invoice No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoiced_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Amount__c</fullName>
    <description>Amount Agreed to be paid by the client</description>
    <label>Invoiced Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoiced_Amount_VAT_16__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Amount_VAT_16__c</fullName>
    <formula>IF(TEXT(Matter__r.Exempted__c) = &quot;NO&quot;, 0.16  * Invoiced_Amount__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoiced Amount VAT 16%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Matter__c.field-meta.xml
<CustomField>
    <fullName>Matter__c</fullName>
    <label>Matter</label>
    <referenceTo>Matter__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Particulars_Rendered__c.field-meta.xml
<CustomField>
    <fullName>Particulars_Rendered__c</fullName>
    <label>Particulars Rendered</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Physical_Address__c.field-meta.xml
<CustomField>
    <fullName>Physical_Address__c</fullName>
    <label>Physical Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Postal_Address__c.field-meta.xml
<CustomField>
    <fullName>Postal_Address__c</fullName>
    <label>Postal Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Select_Address_On_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Select_Address_On_Invoice__c</fullName>
    <label>Change Address On Invoice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent Matter Client Address</fullName>
            </value>
            <value>
                <fullName>Adverse Party Address</fullName>
            </value>
            <value>
                <fullName>New Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_of_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Total_of_Invoice__c</fullName>
    <formula>Invoiced_Amount__c +  Invoiced_Amount_VAT_16__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total of Invoice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disbursements</fullName>
            </value>
            <value>
                <fullName>Legal Fees</fullName>
                <default>true</default>
                <label>Legal Fees</label>
            </value>
            <value>
                <fullName>Proforma Invoice/Fee Note</fullName>
            </value>
            <value>
                <fullName>Hisa Disbursment</fullName>
            </value>
            <value>
                <fullName>Hisa Secretarial Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matter__c/Matter__c.object-meta.xml
<CustomObject>
    <label>Matter</label>
    <nameField>
        <label>Matter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Matter__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Legal Fee</description>
    <label>Legal Fees</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Matters (Client)</relationshipLabel>
    <relationshipName>Matters1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&quot;1. Give a detailed background or history of the matter. 2. What is the legal analysis of the issues in this matter. 3. Briefly summarize the client instructions with deliverables. 4. What is the timeline for this matter. 5. What are the agreed terms of payment (if any)&quot;</defaultValue>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Initials_and_Current_Date__c.field-meta.xml
<CustomField>
    <fullName>Initials_and_Current_Date__c</fullName>
    <formula>Advocate_s_Initials__c +&quot;/&quot;+ Current_Month_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Initials and Current Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Job_No__c.field-meta.xml
<CustomField>
    <fullName>Job_No__c</fullName>
    <label>Job No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Our_Ref_2__c.field-meta.xml
<CustomField>
    <fullName>Our_Ref_2__c</fullName>
    <description>File number + Job Number</description>
    <formula>IF(
AND(
NOT(ISBLANK(Parent_Name__c)),
OR(
ISPICKVAL(Practice_Area__c, &quot;Real Estate Development (Property File)&quot;),
ISPICKVAL(Practice_Area__c, &quot;Intellectual Property (Property file)&quot;),
ISPICKVAL(Practice_Area__c, &quot;Litigation (Property File)&quot;)
)
),
File_No__c &amp; &quot;/ &quot; &amp;
IF(
ISPICKVAL(Department__c, &quot;Secretarial&quot;),
Hisa_Job_No__c,
Job_No__c
) &amp;
&quot;-&quot; &amp; (Unit_Description__c),
File_No__c &amp; &quot;/ &quot; &amp;
IF(
ISPICKVAL(Department__c, &quot;Secretarial&quot;),
Hisa_Job_No__c,
Job_No__c
)
)</formula>
    <label>Our Ref</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Particulars_Rendered__c.field-meta.xml
<CustomField>
    <fullName>Particulars_Rendered__c</fullName>
    <description>Writeup for legal services rendered to appear on the invoice</description>
    <inlineHelpText>Writeup for legal services rendered to appear on the invoice</inlineHelpText>
    <label>Particulars Rendered</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Physical_Address__c.field-meta.xml
<CustomField>
    <fullName>Physical_Address__c</fullName>
    <description>Adverse Party Physical Address</description>
    <label>Adverse Party Physical Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Postal_Address__c.field-meta.xml
<CustomField>
    <fullName>Postal_Address__c</fullName>
    <description>Adverse Party Postal Address</description>
    <label>Adverse Party Postal Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <description>Matter Amount + VAT</description>
    <formula>Amount__c +  VAT_16__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub-Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Matter__c/fields/VAT_16__c.field-meta.xml
<CustomField>
    <fullName>VAT_16__c</fullName>
    <formula>IF(TEXT(Exempted__c) = &quot;NO&quot;, 0.16 *  Amount__c , 0)</formula>
    <label>VAT 16%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoicePDFControllerDisbursement.cls
public with sharing class InvoicePDFControllerDisbursement {
    
    public Invoice__c inv { get; set; }
    public List<Matter_Item__c> matterItems { get; set; }
    public Decimal totalAmount { get; set; }
    
    public List<Matter_Item__c> particularsItems { get; set; }
    public List<Matter_Item__c> disbursementItems { get; set; }
    
    //hiiiiiiiiiyyy
    public Decimal particularsTotal { get; set; }
    public Decimal particularsTotalWithVAT { get; set; }
    public Decimal disbursementTotal { get; set; }
    public Decimal disbursementTotalWithVAT { get; set; }
    public Decimal grandTotal { get; set; }

    public InvoicePDFControllerDisbursement() {

        String idParam = ApexPages.currentPage().getParameters().get('id');

        if (String.isBlank(idParam)) {
            inv = new Invoice__c();
            matterItems = new List<Matter_Item__c>();
            totalAmount = 0;
            return;
        }

        try {
            inv = [
                SELECT Id, Invoice_No__c, Date__c, Client_Name__c,Name, Disbursement_Amount_Requested__c,Particulars_Rendered__c,Include_Logo__c,
                       Initials_and_Current_Date__c,Invoiced_Amount__c, Invoiced_Amount_VAT_16__c, Total_of_Invoice__c,Invoice_Number__c,
                       Matter__r.Id, Matter__r.Name, Matter__r.Job_No__c, Matter__r.Our_Ref_2__c,
                	   Matter__r.Amount__c, Matter__r.VAT_16__c, Matter__r.Sub_Total__c,Type__c,
                       Matter__r.Client__r.Physical_Address__c,Select_Address_On_Invoice__c,Postal_Address__c,Adverse_Party_Invoice_Postal_Address__c,
                       Matter__r.Client__r.Postal_Address__c,Bank_Account_Name__c,Disbursement_Invoice_Number__c
                FROM Invoice__c
                WHERE Id = :idParam
                LIMIT 1
            ];

            // Fetch Matter Item records
            matterItems = [
                SELECT Id, Description__c, Amount__c, Appear_on_Invoice__c, Line_Type__c, Quantity__c, Unit_Price__c, Grand_Total__c
                FROM Matter_Item__c
                WHERE Matter__c = :inv.Matter__r.Id AND Appear_on_Invoice__c = True
                ORDER BY CreatedDate ASC
            ];

            // Calculate Total Amount
            totalAmount = 0;
            for (Matter_Item__c mi : matterItems) {
                if (mi.Amount__c != null)
                    totalAmount += mi.Amount__c;
            }
            
        particularsItems = new List<Matter_Item__c>();
        disbursementItems = new List<Matter_Item__c>();

        particularsTotal = 0;
        disbursementTotal = 0;

        for (Matter_Item__c mi : matterItems) {

            if (mi.Line_Type__c == 'Particulars Rendered') {
                particularsItems.add(mi);
                if (mi.Grand_Total__c != null)
                    particularsTotal += mi.Grand_Total__c;
            }

            else if (mi.Line_Type__c == 'Disbursement') {
                disbursementItems.add(mi);
                if (mi.Grand_Total__c != null)
                    disbursementTotal += mi.Grand_Total__c;
            }
        }
         
		particularsTotalWithVAT = particularsTotal + particularsTotal * 0.16;
        disbursementTotalWithVAT = disbursementTotal + disbursementTotal * 0.16;
        grandTotal = particularsTotalWithVAT + disbursementTotalWithVAT;

        } catch (Exception e) {
            inv = new Invoice__c();
            matterItems = new List<Matter_Item__c>();
            totalAmount = 0;
        }
    }
    
    
}